language: java
install: skip

os: linux
dist: trusty
jdk: openjdk11
# jdk: openjdk8
# jdk: oraclejdk8

script:
    # Download and install JPM
    - wget https://raw.githubusercontent.com/jpm4j/jpm4j.installers/master/dist/biz.aQute.jpm.run.jar
    - sudo java -jar biz.aQute.jpm.run.jar init
    # Install BLADE
    - sudo jpm install -f https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/blade/com.liferay.blade.cli//4.0.8/com.liferay.blade.cli-4.0.8.jar
    # Create an empty Liferay workspace
    - cd ..
    - blade init -v portal-7.3-ga6 liferay-workspace
    # Copy sources to modules directory
    - cd liferay-workspace
    - cp -r /home/travis/build/chrberndt/liferay-todo-list modules
    # Download Liferay bundle
    - ./gradlew initBundle
    # Build service classes
    - ./gradlew :modules:liferay-todo-list:liferay-todo-list-service:buildService
    # Run integration tests
    - ./gradlew :modules:liferay-todo-list:liferay-todo-list-test:testIntegration
