language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
    - pwd; ls -lh
    # Download and install JPM
    - wget https://raw.githubusercontent.com/jpm4j/jpm4j.installers/master/dist/biz.aQute.jpm.run.jar
    - sudo java -jar biz.aQute.jpm.run.jar init
    # Install BLADE
    - sudo jpm install -f https://repository-cdn.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/blade/com.liferay.blade.cli//4.0.8/com.liferay.blade.cli-4.0.8.jar
    # Check setup
    #- java -version
    #- blade version
    #- which blade
    # Create an empty Liferay workspace
    - blade init -v portal-7.3-ga6 ../liferay-workspace
    # Copy sources to modules directory
    - cp -r /home/travis/build/chrberndt/liferay-todo-list ../liferay-workspace/modules
    # Download Liferay bundle
    - ../liferay-workspace/gradlew initBundle
