# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Download JPM
      run: wget https://raw.githubusercontent.com/jpm4j/jpm4j.installers/master/dist/biz.aQute.jpm.run.jar
    - name: Install JPM
      run: sudo java -jar biz.aQute.jpm.run.jar init
     # run: java -jar biz.aQute.jpm.run.jar --home ~ init
    # - name: Add user's ~/bin directory to PATH
    #  run: export PATH="~/bin:$PATH"
    - name: Install BLADE
      run: sudo jpm install -f https://releases.liferay.com/tools/blade-cli/latest/blade.jar
    - name: Update BLADE to the latest release
      run: sudo blade update
    - name: Create an empty Liferay workspace
      run: blade init -v portal-7.3-ga7 liferay-workspace
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Copy sources
      run: cp -r /home/runner/work/liferay-todo-list/liferay-todo-list liferay-workspace/modules/
    - name: Setup gradlew
      working-directory: ./liferay-workspace
      run: chmod +x gradlew
    - name: Download Liferay bundle
      working-directory: ./liferay-workspace
      run: ./gradlew initBundle
    - name: Generate service builder classes
      working-directory: ./liferay-workspace
      run: ./gradlew buildService
    - name: Run integration tests
      working-directory: ./liferay-workspace
      run: ./gradlew testIntegration
    # - name: Grant execute permission for gradlew
    # - run: chmod +x gradlew
    # - name: Build with Gradle
    # - run: ./gradlew build
