# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Download JPM
      run: wget https://raw.githubusercontent.com/jpm4j/jpm4j.installers/master/dist/biz.aQute.jpm.run.jar
    - name: Install JPM
      run: sudo java -jar biz.aQute.jpm.run.jar init
    - name: Install BLADE
      run: sudo jpm install -f https://releases.liferay.com/tools/blade-cli/latest/blade.jar
    - name: Update BLADE to the latest release
      run: sudo blade update
    - name: Create an empty Liferay workspace
      working-directory: /opt/
      run: blade init -v portal-7.3-ga6 liferay-workspace
    - name: Copy sources
      working-directory: /opt/liferay-workspace/modules
      run: cp -r /home/runner/work/liferay-todo-list/liferay-todo-list .
    - name: Setup gradlew
      working-directory: /opt/liferay-workspace
      run: chmod +x gradlew
    - name: Download Liferay bundle
      working-directory: /opt/liferay-workspace
      run: ./gradlew initBundle
    - name: Generate service builder classes
      working-directory: /opt/liferay-workspace
      run: ./gradlew :modules:liferay-todo-list:liferay-todo-list-service:buildService
    - name: Run integration tests
      working-directory: /opt/liferay-workspace
      run: ./gradlew :modules:liferay-todo-list:liferay-todo-list-test:testIntegration
    - name: GitHub Pages
      if: ${{ always() }}     
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-github-pages@b8f8d291c97fe0edd9fb4ee73018163593418e8f
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        # Git domain (default github.com)
        # domain: # optional, default is github.com
        # GitHub repository where assets will be deployed (default $GITHUB_REPOSITORY)
        # repo: # optional
        # Git branch where assets will be deployed
        # target_branch: # optional, default is gh-pages
        # Create incremental commit instead of doing push force
        # keep_history: # optional, default is false
        # Allow an empty commit to be created
        # allow_empty_commit: # optional, default is true
        # Build directory to deploy
        build_dir: /opt/liferay-workspace/modules/liferay-todo-list/liferay-todo-list-test/build/reports/tests/testIntegration
        # The committer name and email address
        # committer: # optional
        # The author name and email address
        # author: # optional
        # Commit message
        # commit_message: # optional
        # Write the given domain name to the CNAME file
        # fqdn: # optional
        # Allow Jekyll to build your site
        # jekyll: # optional, default is true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
