# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Download JPM
      run: wget https://raw.githubusercontent.com/jpm4j/jpm4j.installers/master/dist/biz.aQute.jpm.run.jar
    - name: Install JPM in the current user's home directory
      run: java -jar biz.aQute.jpm.run.jar --home ~ init
    - name: Add user's ~/bin directory to PATH
      run: export PATH="$HOME/bin:$PATH"
    - name: Install BLADE
      run: jpm install -f https://releases.liferay.com/tools/blade-cli/latest/blade.jar
    - name: Update BLADE to the latest release
      run: blade update
    # - name: Grant execute permission for gradlew
    # - run: chmod +x gradlew
    # - name: Build with Gradle
    # - run: ./gradlew build
